version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    resource_class: 2xlarge+
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -f cakeRELEASE.Dockerfile -t cake:latest .
