version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -f cakeRELEASE.Dockerfile -t cake:latest .
