name: Debug2.0

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        api-level: [29]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Flutter action
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"
          channel: stable

      - name: Debug
        run: |
          ls /usr/local/lib/android/sdk
          ls /usr/local/lib/android/sdk/*/*
          flutter doctor
          python --version
          python3 --version
